services:
  shade-agent-app:
    environment:
      AGENT_CONTRACT_ID: ${AGENT_CONTRACT_ID}
      SPONSOR_ACCOUNT_ID: ${SPONSOR_ACCOUNT_ID}
      SPONSOR_PRIVATE_KEY: ${SPONSOR_PRIVATE_KEY}
      NETWORK_ID: ${NETWORK_ID}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET}
      GROQ_API_KEY: ${GROQ_API_KEY}
      OPENAI_KEY: ${OPENAI_KEY}
      NEAR_AI_API_KEY: ${NEAR_AI_API_KEY}
      MAINTAINER_SECRET: ${MAINTAINER_SECRET}
      BACKEND_URL: ${BACKEND_URL}
      BACKEND_CALLBACK_URL: ${BACKEND_CALLBACK_URL}
    platform: linux/amd64
    image: jerrygeorge/holy@sha256:7c3be5bad0702688cf07a89c13256f90f06183592f725739933fb3dad1286b56
    container_name: shade-agent-app
    ports:
      - 3000:3000
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    restart: always
